# upload the front end code and run the webserver

- name: upload the front end code
  become: yes
  copy:
    src: ../../../web
    dest: /home/ubuntu/

- name: run the webserver
  become: yes
  command: docker run -d -p 80:80 -v /home/ubuntu/web/visualization:/usr/local/apache2/htdocs --name webserver httpd
