- hosts: database
  remote_user: ubuntu
  gather_facts: false
  pre_tasks:
  - name: 'install python2'
    raw: sudo apt-get update; sudo apt-get -y install python

  roles:
    - role: upload-and-execute
