# - name: output content to a file
#   vars:
#     content: "{{ ansible_architecture }}"
#   template: src=hello.j2 dest=./hello.txt

- name: output to a bash script
  vars:
    instance_ip0: "115.146.84.221"
    instance_ip1: "115.146.84.248"
    instance_ip2: "115.146.84.31"
  template: src=masternode.sh.j2 dest=./masternode.sh
