# - hosts: localhost
#   vars_files:
#     - variables/variables.yml
#   gather_facts: true

#   roles:
#     - role: openstack-common
#     - role: openstack-images
#     - role: openstack-security-groups
#     - role: openstack-instance

# - hosts: all_servers
#   remote_user: ubuntu
#   become: true
#   gather_facts: true
#   tasks:
#     - name: 'add proxy'
#       lineinfile: 
#         dest: /etc/environment
#         line: "http_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nhttps_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nftp_proxy=\"http://wwwproxy.unimelb.edu.au:8000\""
      

# - hosts: all_servers
#   remote_user: ubuntu
#   gather_facts: true
#   pre_tasks:
#     - name: 'install python2'
#       raw: sudo apt-get update; sudo apt-get -y install python

#   roles:
#     - role: docker-configuration

- hosts: subnode1
  remote_user: ubuntu
  gather_facts: true

  roles:
    - role: couchdb-subnode1

- hosts: subnode2
  remote_user: ubuntu
  gather_facts: true

  roles:
    - role: couchdb-subnode2

- hosts: masternode
  remote_user: ubuntu
  gather_facts: true

  roles:
    - role: couchdb-masternode
